import React from 'react';

export default function IntentPage() {
  return (
    <div className="space-y-6">
      <h1 className="text-4xl font-extrabold text-white tracking-tight mb-2">Semantic Intent Classification</h1>
      <p className="text-lg text-slate-300 leading-relaxed">
        Unlike rigid keyword regexes, Whisper Bot translates user queries into control commands using semantic proximity vectors generated by a local sentence-transformer.
      </p>

      <h2 className="text-2xl font-bold text-white mt-8 mb-4">Intent Engine Workflow</h2>
      <ol className="list-decimal pl-6 space-y-3 text-slate-300">
        <li><strong>Model:</strong> <code>all-MiniLM-L6-v2</code> sentence transformer compiled to ONNX format. Maps any natural language sentence into a 384-dimensional floating-point vector.</li>
        <li><strong>Embedding Generation:</strong> The model extracts token features and performs mean pooling over the sequence dimension to yield a single embedding vector.</li>
        <li><strong>Proximity Comparison:</strong> The query vector is compared against a pre-compiled database of 28 movement intents using Cosine Similarity.</li>
      </ol>

      <div className="border border-white/10 rounded-xl p-6 bg-slate-900/50 my-6">
        <h3 className="text-xl font-bold text-white mb-2">Mathematical Formulation</h3>
        <p className="text-sm text-slate-300 leading-relaxed">
          Cosine similarity measures the angular distance between the query vector A and intent vector B:
          <br /><br />
          <code className="text-purple-400">Similarity = (A · B) / (||A|| * ||B||)</code>
          <br /><br />
          Since all embeddings in our database are pre-normalized to unit length (||A|| = ||B|| = 1), the calculation simplifies to a simple dot product:
          <br /><br />
          <code className="text-purple-400">Similarity = A · B</code>
        </p>
      </div>
    </div>
  );
}
